/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DiskSHA1Encoder */

#ifndef _Included_DiskSHA1Encoder
#define _Included_DiskSHA1Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DiskSHA1Encoder
 * Method:    encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DiskSHA1Encoder_encode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
